const ppeByJob={"Ramp Agent / Fleet Service":["High-visibility vest or reflective outerwear","Safety shoes / protective footwear","Hearing protection near aircraft, GSE, or loud areas","Task-appropriate gloves","Eye protection when exposed to splash, dust, debris, chemicals, or pressurized systems","Weather PPE when needed: rain gear, cooling PPE, or cold-weather gear"],"Bagroom / Baggage Sortation":["Safety shoes","Gloves for baggage handling","Hearing protection where required","Ergonomic controls: mats, rotation, team lifts, and belt-height awareness","High-visibility gear if exposed to ramp traffic"],"Lavatory / Potable Water Service":["High-visibility vest","Safety shoes","Chemical-resistant gloves","Eye or face protection where splash is possible","Hand-washing and sanitation supplies","Spill-response materials"],"GSE / Equipment Support":["High-visibility vest","Safety shoes","Cut-resistant or task-appropriate gloves","Eye protection","Hearing protection near aircraft or loud equipment","Out-of-service / tag-out process when equipment is unsafe"]};
const freezeSteps=["Stop work and protect people from immediate danger.","Call emergency response if anyone is hurt or symptoms are serious.","Secure the area with cones, tape, barricades, or a person posted at the scene.","Do not move equipment, tools, ladders, cords, vehicles, or materials unless life safety requires it.","Identify witnesses and separate them when possible before stories blend together.","Take photos: wide view, middle view, and close-up view.","Write down time, weather, lighting, staffing, radio status, equipment ID, and who was present.","Preserve defective equipment, PPE, forms, messages, and training records.","Submit the correct safety, injury, GSAP/ASAP, or company report.","Assign follow-up ownership so the issue does not disappear without correction."];
let checked=[];document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active-panel'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active-panel')}));
function val(id){return document.getElementById(id).value}function copyText(id){navigator.clipboard.writeText(document.getElementById(id).innerText);alert('Copied!')}
const oshaStandards={
  ppe:{title:"PPE / Hazard Assessment",standard:"29 CFR 1910.132",link:"https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.132",plain:"Employers must assess the workplace for hazards, select PPE that protects workers from those hazards, make sure PPE fits, train affected workers, and keep PPE sanitary and reliable.",ramp:"Use this when workers are exposed to hazards such as noise, sharp edges, chemicals, dust, weather, moving equipment, or other conditions requiring protective equipment."},
  pit:{title:"Powered Industrial Trucks / Unsafe Equipment",standard:"29 CFR 1910.178",link:"https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.178",plain:"Powered industrial trucks must be operated safely, operators must be trained and evaluated, and equipment that is defective, unsafe, or in need of repair must be taken out of service until restored to safe operating condition.",ramp:"Use this for forklifts, tugs, tractors, beltloaders, or other powered equipment concerns such as brakes, steering, leaks, alarms, visibility, training, or unsafe operation."},
  noise:{title:"Noise / Hearing Conservation",standard:"29 CFR 1910.95",link:"https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.95",plain:"Employers must protect workers from harmful occupational noise exposure and implement hearing conservation requirements when exposure reaches OSHA action levels.",ramp:"Use this when workers are exposed to aircraft, GSE, bagroom, or other high-noise areas where hearing protection, monitoring, training, or enforcement may be needed."},
  hazcom:{title:"Hazard Communication / Chemicals",standard:"29 CFR 1910.1200",link:"https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.1200",plain:"Employers must provide information about hazardous chemicals through labels, safety data sheets, and employee training so workers understand chemical hazards and protective measures.",ramp:"Use this for glycol, fuel, lavatory chemicals, cleaning products, battery acid, unknown odors, unlabeled containers, or missing SDS information."},
  firstaid:{title:"Medical Services / First Aid",standard:"29 CFR 1910.151",link:"https://www.osha.gov/laws-regs/regulations/standardnumber/1910/1910.151",plain:"Employers must ensure medical advice and consultation are available. When a clinic or hospital is not near the workplace, trained first-aid personnel and adequate first-aid supplies must be available. Emergency eyewash or drenching facilities are required where corrosive materials may contact eyes or body.",ramp:"Use this for first-aid coverage, emergency response access, eyewash/shower concerns, corrosive chemical exposure, and whether supplies or trained responders are available."},
  gdc:{title:"General Duty Clause",standard:"OSH Act Section 5(a)(1) / 29 USC 654(a)(1)",link:"https://www.osha.gov/laws-regs/oshact/section5-duties",plain:"Employers must provide a workplace free from recognized hazards that are causing or are likely to cause death or serious physical harm.",ramp:"Use this when there may not be a specific OSHA rule covering the exact hazard, but the hazard is recognized, serious, and preventable."}
};
function runStandards(){let key=val('standardTopic');let s=oshaStandards[key];document.getElementById('standardTitle').innerText=`${s.title} — ${s.standard}`;document.getElementById('standardLink').href=s.link;document.getElementById('standardOutput').innerText=`OSHA Standard Reference\n\nTopic: ${s.title}\nStandard: ${s.standard}\n\nPlain-language meaning:\n${s.plain}\n\nRamp / workplace use:\n${s.ramp}\n\nRecommended action:\n1. Document the condition with facts, photos, location, date, and who was exposed.\n2. Protect workers from immediate exposure.\n3. Report through the proper safety concern, injury, GSAP/ASAP, or company process.\n4. Verify the official OSHA standard and company/local policy before making a final compliance decision.\n\nOfficial OSHA link: ${s.link}`;}

function runOsha(){let score=0;if(val('oshaExposure').includes('actively'))score+=40;if(val('oshaControl').includes('No effective'))score+=35;if(val('oshaHistory').includes('reported')||val('oshaHistory').includes('before'))score+=25;let risk=score>=75?'High Concern — Escalate and Document':score>=40?'Moderate Concern — Correct and Monitor':'Lower Concern — Verify and Close the Loop';document.getElementById('oshaRisk').innerText=risk;document.getElementById('oshaOutput').innerText=`OSHA / Workplace Safety Quick Check\n\nHazard: ${val('oshaHazard')}\nExposure: ${val('oshaExposure')}\nCurrent control: ${val('oshaControl')}\nHistory: ${val('oshaHistory')}\n\nRisk Level: ${risk}\n\nSuggested next steps:\n1. Protect workers from immediate exposure.\n2. Notify supervision and the safety representative.\n3. Take photos and document the condition.\n4. Submit the concern through the proper reporting process.\n5. Assign someone to follow up and confirm correction.\n\nReminder: Verify all final actions with OSHA rules, company policy, airport rules, and local procedures.`}
function runReport(){document.getElementById('reportOutput').innerText=`Suggested Safety Report Wording\n\nDuring ${val('reportTask')}, ${val('reportIssue')}. This created a safety concern because ${val('reportHazard')}. The outcome was: ${val('reportOutcome')}.\n\nI am reporting this in good faith so the event can be reviewed for contributing factors, including staffing, time pressure, task overlap, communication, weather, delays, equipment availability, and whether the current process gives the crew enough time and resources to follow SOP without shortcuts.\n\nSuggested corrective focus:\n1. Review staffing and task assignment.\n2. Verify whether SOP steps were realistic under the conditions.\n3. Identify whether additional training, manpower, equipment, or process change is needed.\n4. Share lessons learned back to frontline workers.`}
function runPpe(){let list=[...ppeByJob[val('ppeJob')]];if(document.getElementById('ppeHeat').checked)list.push('Cooling PPE, water access, shade/cool-down access, and heat illness monitoring');if(document.getElementById('ppeCold').checked)list.push('Cold-weather gloves, insulated layers, traction awareness, and warm-up breaks');if(document.getElementById('ppeChemical').checked)list.push('Chemical-specific SDS review and splash protection');if(document.getElementById('ppeDust').checked)list.push('Dust exposure evaluation; respiratory protection only through a proper program and fit testing');document.getElementById('ppeOutput').innerText=`PPE Requirement Check\n\nJob: ${val('ppeJob')}\n\nRecommended PPE / controls:\n${list.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nReminder: Verify requirements with company policy, OSHA standards, SDS, airport rules, and local procedures.`}
function runHeat(){let T=Number(val('heatTemp')),R=Number(val('heatHumidity'));let hi=Math.round(-42.379+2.04901523*T+10.14333127*R-.22475541*T*R-.00683783*T*T-.05481717*R*R+.00122874*T*T*R+.00085282*T*R*R-.00000199*T*T*R*R);let adjusted=hi+(val('heatWorkload')==='Moderate'?4:val('heatWorkload')==='Heavy'?8:0);let guide=adjusted>=105?'High Risk — Increase cool-down breaks, rotate workers, monitor symptoms, provide shade/cooling, and consider stopping or modifying work if controls are not effective.':adjusted>=95?'Caution — Use water, rest, shade, acclimatization, buddy checks, and supervisor monitoring. Increase breaks for heavy work or direct sun.':'Lower Flag — Continue hydration, routine breaks, and symptom awareness. Conditions can change quickly.';document.getElementById('heatTitle').innerText=`Estimated Heat Index: ${hi}°F`;document.getElementById('heatOutput').innerText=`Heat Index / Work-Rest Field Check\n\nTemperature: ${T}°F\nHumidity: ${R}%\nEstimated Heat Index: ${hi}°F\nWorkload: ${val('heatWorkload')}\n\nRecommendation: ${guide}\n\nReminder: Consider direct sun, hot pavement, aircraft heat, PPE, poor airflow, overtime, staffing shortages, and acclimatization.`}
function renderFreeze(){let list=document.getElementById('freezeList');list.innerHTML='';freezeSteps.forEach((s,i)=>{let b=document.createElement('button');b.className='step '+(checked.includes(i)?'done':'');b.innerText=(checked.includes(i)?'✓':'○')+` Step ${i+1}: ${s}`;b.onclick=()=>{checked=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];renderFreeze()};list.appendChild(b)});document.getElementById('freezeOutput').innerText=`Freeze the Scene Checklist\n\n${freezeSteps.map((s,i)=>`${checked.includes(i)?'[x]':'[ ]'} ${i+1}. ${s}`).join('\n')}`}
function resetFreeze(){checked=[];renderFreeze()}runOsha();runReport();runPpe();runHeat();renderFreeze();runStandards();
.disclaimer-box {
  background-color: #b91c1c; /* strong red */
  color: #ffffff;
  border-left: 6px solid #7f1d1d;
  padding: 14px 18px;
  margin: 30px auto;
  max-width: 900px;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
}
